name: Docker Image CI
on:
  push:
    branches: [ "15.0" ]
  pull_request:
    branches: [ "15.0" ]
jobs:
  build:
    runs-on: ubuntu-latest
    env:
      GITHUB_SHA_SHORT: ${GITHUB_SHA::6}
    steps:
    - uses: actions/checkout@v3
    - name: Compute git short sha
      run: echo "GITHUB_SHA_SHORT=$(echo $GITHUB_SHA | cut -c 1-7)" >> $GITHUB_ENV
    - name: Build the Docker image
      run: docker image build --target=prod --tag hamodoo:$GITHUB_ENV .
