name: Pipeline

on:
  push:
    branches: [ "15.0" ]
  pull_request:
    branches: [ "15.0" ]

env:
  IMAGE_NAME: sardylan/hamodoo
  IMAGE_TAG: ${{ github.head_ref || github.ref_name }}

jobs:
  build-test:
    name: "Image build and test"
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres:14.4-alpine
        env:
          POSTGRES_USER: "hamodoo"
          POSTGRES_PASSWORD: "hamodoo"
        options: --health-cmd pg_isready --health-interval 10s --health-timeout 5s --health-retries 5
        network: ci
    steps:
    - uses: actions/checkout@v3
      with:
        submodules: true
    - name: Login to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}
    - name: Build the Docker image
      run: docker image build --target=prod --tag ${IMAGE_NAME}:${IMAGE_TAG} .
    - name: Run tests
      run: docker container run --rm --network ci -e TEST_FLAGS="-i ham_award --test-tags /ham_award" -e DB_USERNAME="hamodoo" -e DB_PASSWORD="hamodoo" -e DB_NAME="hamodoo" sardylan/hamodoo:${IMAGE_TAG}
    - name: Tag the image
      run: docker image tag sardylan/hamodoo:${IMAGE_TAG} sardylan/hamodoo:latest sardylan/hamodoo:${GITHUB_REF_NAME}
    - name: Push images
      run: docker image push sardylan/hamodoo:latest sardylan/hamodoo:${GITHUB_REF_NAME}
